production:
  periodic_cleanup:
    class: DestroyStalePointingSessionsJob
    queue: background
    args: [ ]
    schedule: every 30 minutes
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
